// Command themegen reads ghostty-format theme files from
// iTerm2-Color-Schemes and emits a Go source file with one
// theme.Palette per file. Run from the repo root:
//
//	go run ./cmd/themegen <ghostty-dir> > internal/theme/generated.go
//
// Re-run when the upstream catalogue updates. Output is committed.
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

type ghosttyTheme struct {
	Name       string
	Background string
	Foreground string
	Palette    [16]string
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: themegen <ghostty-themes-dir>")
		os.Exit(1)
	}
	dir := os.Args[1]
	entries, err := os.ReadDir(dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", dir, err)
		os.Exit(1)
	}
	var themes []ghosttyTheme
	seenIDs := map[string]bool{}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		path := filepath.Join(dir, e.Name())
		t, err := parseTheme(path, e.Name())
		if err != nil {
			fmt.Fprintf(os.Stderr, "skip %s: %v\n", e.Name(), err)
			continue
		}
		// Sanity: must have a background + foreground + at least basic
		// palette colours.
		if t.Background == "" || t.Foreground == "" {
			continue
		}
		if t.Palette[1] == "" || t.Palette[4] == "" {
			continue
		}
		// Dedupe by id (slugified name).
		id := slugify(t.Name)
		if seenIDs[id] {
			continue
		}
		seenIDs[id] = true
		themes = append(themes, t)
	}
	sort.Slice(themes, func(i, j int) bool {
		return themes[i].Name < themes[j].Name
	})

	// Emit generated.go.
	w := bufio.NewWriter(os.Stdout)
	fmt.Fprintln(w, "// Code generated by themegen. DO NOT EDIT.")
	fmt.Fprintln(w, "// Source: github.com/mbadolato/iTerm2-Color-Schemes (ghostty/)")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "package theme")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// generatedPalettes is the imported catalogue. Populated at")
	fmt.Fprintln(w, "// init time into the global Palettes() registry.")
	fmt.Fprintln(w, "var generatedPalettes = []Palette{")
	for _, t := range themes {
		emitPalette(w, t)
	}
	fmt.Fprintln(w, "}")
	w.Flush()
}

func parseTheme(path, name string) (ghosttyTheme, error) {
	f, err := os.Open(path)
	if err != nil {
		return ghosttyTheme{}, err
	}
	defer f.Close()

	t := ghosttyTheme{Name: name}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		eq := strings.IndexByte(line, '=')
		if eq < 0 {
			continue
		}
		key := strings.TrimSpace(line[:eq])
		val := strings.TrimSpace(line[eq+1:])
		switch {
		case key == "background":
			t.Background = val
		case key == "foreground":
			t.Foreground = val
		case strings.HasPrefix(key, "palette"):
			// "palette = 4" or "palette" (with the index after =)
			rest := strings.TrimPrefix(key, "palette")
			rest = strings.TrimSpace(rest)
			// In ghostty format: "palette = 4=#hex" — so val is "4=#hex"
			// or key already absorbed the index. Handle both shapes.
			idx, hex := splitIdxHex(rest, val)
			if idx < 0 || idx > 15 || hex == "" {
				continue
			}
			t.Palette[idx] = hex
		}
	}
	return t, sc.Err()
}

// splitIdxHex normalises ghostty's quirky "palette = 0=#hex" line shape.
// keyTail may be "" or "0"; val may be "0=#hex" or "#hex".
func splitIdxHex(keyTail, val string) (int, string) {
	// Case 1: keyTail is "", val is "0=#hex".
	if keyTail == "" {
		if eq := strings.IndexByte(val, '='); eq >= 0 {
			idx := atoi(val[:eq])
			return idx, strings.TrimSpace(val[eq+1:])
		}
		return -1, ""
	}
	// Case 2: keyTail is "0", val is "#hex".
	return atoi(keyTail), val
}

func atoi(s string) int {
	s = strings.TrimSpace(s)
	if s == "" {
		return -1
	}
	n := 0
	for _, r := range s {
		if r < '0' || r > '9' {
			return -1
		}
		n = n*10 + int(r-'0')
	}
	return n
}

// slugify lowercases + replaces non-alphanumerics with "-".
func slugify(s string) string {
	var b strings.Builder
	prevDash := false
	for _, r := range strings.ToLower(s) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
			prevDash = false
			continue
		}
		if !prevDash && b.Len() > 0 {
			b.WriteByte('-')
			prevDash = true
		}
	}
	return strings.Trim(b.String(), "-")
}

// emitPalette writes one Palette literal. Mapping from the 16-colour
//   - bg/fg ghostty shape into our palette is opinionated:
//     Bg        ← background
//     BgAlt     ← palette[0] (terminal "black")
//     Panel     ← palette[0] (same — most themes use one bg tier)
//     Border    ← palette[8] (terminal bright black / "grey")
//     BorderHi  ← palette[12] when present, else palette[4] (bright blue / blue)
//     Fg        ← foreground
//     FgDim     ← palette[8]
//     Muted     ← palette[8]
//     Blue      ← palette[12] when present, else palette[4]
//     Cyan      ← palette[14] when present, else palette[6]
//     Green     ← palette[10] when present, else palette[2]
//     Yellow    ← palette[11] when present, else palette[3]
//     Red       ← palette[9]  when present, else palette[1]
//     Magenta   ← palette[13] when present, else palette[5]
//     Orange    ← palette[3]  (yellow-ish; warm enough for our usage)
func emitPalette(w *bufio.Writer, t ghosttyTheme) {
	id := slugify(t.Name)
	fmt.Fprintf(w, "\t{Name: %q, ID: %q,\n", t.Name, id)
	fmt.Fprintf(w, "\t\tBg: hex(%q), BgAlt: hex(%q), Panel: hex(%q),\n",
		t.Background, pick(t.Palette[0], t.Background), pick(t.Palette[0], t.Background))
	fmt.Fprintf(w, "\t\tBorder: hex(%q), BorderHi: hex(%q),\n",
		pick(t.Palette[8], t.Foreground), pick(t.Palette[12], t.Palette[4]))
	fmt.Fprintf(w, "\t\tFg: hex(%q), FgDim: hex(%q), Muted: hex(%q),\n",
		t.Foreground, pick(t.Palette[8], t.Foreground), pick(t.Palette[8], t.Foreground))
	fmt.Fprintf(w, "\t\tBlue: hex(%q), Cyan: hex(%q), Green: hex(%q),\n",
		pick(t.Palette[12], t.Palette[4]), pick(t.Palette[14], t.Palette[6]), pick(t.Palette[10], t.Palette[2]))
	fmt.Fprintf(w, "\t\tYellow: hex(%q), Red: hex(%q), Magenta: hex(%q), Orange: hex(%q)},\n",
		pick(t.Palette[11], t.Palette[3]), pick(t.Palette[9], t.Palette[1]), pick(t.Palette[13], t.Palette[5]), pick(t.Palette[3], t.Palette[1]))
}

func pick(primary, fallback string) string {
	if primary == "" {
		return fallback
	}
	return primary
}
