package ui

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/Jacob-Stokes/sf-deck/internal/devproject"
)

// SeedDemoDevProjects writes the fixture project/bundle/tag/saved
// world into the throwaway devprojects.db. demoDir is the tmpdir
// app.Open allocated; bundles get on-disk skeletons under
// <demoDir>/bundles/ so the bundle detail view's "stale" check
// passes (which would otherwise hide the rows on entry).
func SeedDemoDevProjects(s *devproject.Store, demoDir string) error {
	if s == nil {
		return nil
	}
	bundleRoot := filepath.Join(demoDir, "bundles")
	if err := os.MkdirAll(bundleRoot, 0o755); err != nil {
		return fmt.Errorf("seed bundle root: %w", err)
	}

	now := time.Now()
	projects := demoDevProjects(now)
	for _, p := range projects {
		if err := s.CreateDevProject(p); err != nil {
			return fmt.Errorf("seed devproject %s: %w", p.ID, err)
		}
	}

	for _, it := range demoDevProjectItems() {
		if _, err := s.AddItem(it); err != nil {
			return fmt.Errorf("seed item %s/%s: %w", it.DevProjectID, it.Ref, err)
		}
	}

	for _, b := range demoDevBundles(bundleRoot) {
		if err := writeDemoBundleSkeleton(b.Path, b.DevProjectID); err != nil {
			return fmt.Errorf("seed bundle skeleton %s: %w", b.Path, err)
		}
		row, err := s.CreateBundle(b.DevProjectID, b.Path, b.DefaultOrgAlias)
		if err != nil {
			return fmt.Errorf("seed bundle row %s: %w", b.Path, err)
		}
		if !b.LastRetrievedAt.IsZero() {
			_ = s.MarkRetrieved(row.ID)
		}
		if !b.LastDeployedAt.IsZero() {
			_ = s.MarkDeployed(row.ID)
		}
	}

	tagIDs := map[string]int64{}
	for _, t := range demoTagSeeds() {
		tag, err := s.CreateTag(t.Name, t.Color, t.Icon)
		if err != nil {
			return fmt.Errorf("seed tag %s: %w", t.Name, err)
		}
		tagIDs[t.Name] = tag.ID
	}
	for _, bind := range demoTagBindings() {
		tagID, ok := tagIDs[bind.TagName]
		if !ok {
			continue
		}
		if err := s.ApplyTag(tagID, bind.Kind, bind.Ref, bind.OrgUser); err != nil {
			return fmt.Errorf("seed tag binding %s/%s: %w", bind.TagName, bind.Ref, err)
		}
	}

	for _, q := range demoSavedQueries() {
		if _, err := s.CreateSavedQuery(q.Name, q.Description, q.Body); err != nil {
			return fmt.Errorf("seed saved query %s: %w", q.Name, err)
		}
	}

	for _, ap := range demoSavedApex() {
		if _, err := s.CreateSavedApex(ap.Name, ap.Description, ap.Body); err != nil {
			return fmt.Errorf("seed saved apex %s: %w", ap.Name, err)
		}
	}

	for _, h := range demoSOQLHistory(now) {
		if _, err := s.LogSOQLHistory(h.OrgUser, h.Body, h.DurationMs, h.RowCount, h.Error); err != nil {
			return fmt.Errorf("seed soql history: %w", err)
		}
	}

	return nil
}

func writeDemoBundleSkeleton(path, projectID string) error {
	if err := os.MkdirAll(filepath.Join(path, "force-app", "main", "default"), 0o755); err != nil {
		return err
	}
	sfdxProject := `{"packageDirectories":[{"path":"force-app","default":true}],"namespace":"","sfdcLoginUrl":"https://login.salesforce.com","sourceApiVersion":"62.0"}`
	if err := os.WriteFile(filepath.Join(path, "sfdx-project.json"), []byte(sfdxProject), 0o644); err != nil {
		return err
	}
	manifest := demoBundleManifestFor(projectID)
	if err := os.WriteFile(filepath.Join(path, "package.xml"), []byte(manifest), 0o644); err != nil {
		return err
	}
	readme := "# Demo bundle\n\nFictional Northwind world. Generated by sf-deck --demo.\n"
	if err := os.WriteFile(filepath.Join(path, "README.md"), []byte(readme), 0o644); err != nil {
		return err
	}
	return nil
}
