package ui

// inventory.go — generates the human-readable docs/surfaces.md
// reference by walking the tabRegistry. Called from
// cmd/inventory/main.go.
//
// Output shape: nested per top-level tab. Each tab block lists:
//   - top-level surface (List/Open/Chips/Activate hooks present?)
//   - subtabs (when applicable) with the same hook breakdown
//   - drill targets (which TabSomethingDetail Enter goes to)
//
// What's auto-derived:
//   - tab + subtab presence and labels
//   - whether a list / open / chips / activate hook is wired
//   - openable Targets() per row type when introspectable
//
// What's NOT auto-derived (and gets a "TODO" or hand-filled in
// docs/surfaces.md after generation):
//   - the human description of what each surface IS
//   - drill destinations (closures aren't introspectable)
//   - sidebar contents
//
// Re-running this overwrites the file; manual notes go in a
// separate Notes section per tab if we want them to survive
// re-generation. For now, the generator emits a single fully
// auto block and the user hand-edits afterwards.

import (
	"fmt"
	"sort"
	"strings"
)

// BuildSurfaceInventoryMarkdown returns the fully-rendered
// markdown inventory of every registered Tab + Subtab.
func BuildSurfaceInventoryMarkdown() string {
	var b strings.Builder

	b.WriteString("# sf-deck surface inventory\n\n")
	b.WriteString("Auto-generated reference of every Tab / Subtab / drill destination,\n")
	b.WriteString("plus the hooks each surface has wired (List / Open / Chips / Activate).\n")
	b.WriteString("Generated by `go run ./cmd/inventory`. Hand-edit human descriptions\n")
	b.WriteString("after running — re-running OVERWRITES the file.\n\n")

	b.WriteString("## How to read this\n\n")
	b.WriteString("- **List** — has a tabulated row list (cursor + search)\n")
	b.WriteString("- **Open** — `o` / `ctrl+o` open the Salesforce Lightning destination\n")
	b.WriteString("- **Chips** — has a chip strip (filter / view-switching)\n")
	b.WriteString("- **Drill** — `enter` drills into a detail tab; arrow shows destination\n")
	b.WriteString("- **Sidebar** — has a right-pane context panel\n\n")

	specs := tabSpecs()

	// Order: top-level tabs first (in registry order via Stem ==
	// self), then drill tabs grouped under their stem.
	tops := []Tab{}
	drills := map[Tab][]Tab{}
	for t, s := range specs {
		if s.Stem == t {
			tops = append(tops, t)
		} else {
			drills[s.Stem] = append(drills[s.Stem], t)
		}
	}
	sort.Slice(tops, func(i, j int) bool { return int(tops[i]) < int(tops[j]) })
	for k := range drills {
		sort.Slice(drills[k], func(i, j int) bool { return int(drills[k][i]) < int(drills[k][j]) })
	}

	for _, t := range tops {
		spec := specs[t]
		writeTabBlock(&b, t, spec, drills[t], specs)
	}
	return b.String()
}

func writeTabBlock(b *strings.Builder, t Tab, spec *TabSpec, drillKids []Tab, all map[Tab]*TabSpec) {
	fmt.Fprintf(b, "## /%s\n\n", t.String())
	writeHookSummary(b, spec)

	if len(spec.Subtabs) > 0 {
		b.WriteString("\n### Subtabs\n\n")
		for _, sub := range spec.Subtabs {
			fmt.Fprintf(b, "#### `%s` — %s\n\n", sub.ID, sub.Label)
			writeSubtabHookSummary(b, sub)
			b.WriteString("\n")
		}
	}

	if len(drillKids) > 0 {
		b.WriteString("\n### Drill destinations\n\n")
		for _, dt := range drillKids {
			ds := all[dt]
			if ds == nil {
				continue
			}
			fmt.Fprintf(b, "#### /%s (drill from /%s)\n\n", dt.String(), t.String())
			writeHookSummary(b, ds)
			if len(ds.Subtabs) > 0 {
				b.WriteString("\n##### Subtabs\n\n")
				for _, sub := range ds.Subtabs {
					fmt.Fprintf(b, "- `%s` — %s — ", sub.ID, sub.Label)
					writeSubtabHookSummaryInline(b, sub)
					b.WriteString("\n")
				}
				b.WriteString("\n")
			}
			b.WriteString("\n")
		}
	}
	b.WriteString("\n---\n\n")
}

func writeHookSummary(b *strings.Builder, spec *TabSpec) {
	if spec == nil {
		return
	}
	bullets := []string{}
	if spec.List != nil {
		bullets = append(bullets, "**List** — yes")
	}
	if spec.Open != nil {
		bullets = append(bullets, "**Open** — `o` / `ctrl+o` wired")
		if spec.Open.Drill != nil {
			bullets = append(bullets, "**Drill** — yes (via Open.Drill)")
		}
	}
	if spec.Chips != nil {
		bullets = append(bullets, fmt.Sprintf("**Chips** — domain `%s`", spec.Chips.Domain))
	}
	if spec.Activate != nil {
		bullets = append(bullets, "**Drill** — yes (via Activate)")
	}
	if spec.Sidebar != nil {
		bullets = append(bullets, "**Sidebar** — yes")
	}
	if spec.Identity != nil {
		bullets = append(bullets, "**Identity** — yes (tag picker / openable lookup)")
	}
	if spec.EnsureData != nil {
		bullets = append(bullets, "**EnsureData** — yes (auto-fetch on entry)")
	}
	if spec.RefreshData != nil {
		bullets = append(bullets, "**RefreshData** — yes (`r` refresh)")
	}
	if len(bullets) == 0 {
		b.WriteString("- _no hooks_ (placeholder)\n")
		return
	}
	for _, line := range bullets {
		fmt.Fprintf(b, "- %s\n", line)
	}
}

func writeSubtabHookSummary(b *strings.Builder, sub SubtabSpec) {
	bullets := []string{}
	if sub.List != nil {
		bullets = append(bullets, "**List** — yes")
	}
	if sub.Open != nil {
		bullets = append(bullets, "**Open** — `o`/`ctrl+o` wired")
		if sub.Open.Drill != nil {
			bullets = append(bullets, "**Drill** — yes (Open.Drill)")
		}
	}
	if sub.Chips != nil {
		bullets = append(bullets, fmt.Sprintf("**Chips** — domain `%s`", sub.Chips.Domain))
	}
	if sub.Activate != nil {
		bullets = append(bullets, "**Drill** — yes (Activate)")
	}
	if sub.Sidebar != nil {
		bullets = append(bullets, "**Sidebar** — yes")
	}
	if sub.Identity != nil {
		bullets = append(bullets, "**Identity** — yes")
	}
	if len(bullets) == 0 {
		b.WriteString("- _no hooks_ (placeholder / stub)\n")
		return
	}
	for _, line := range bullets {
		fmt.Fprintf(b, "- %s\n", line)
	}
}

func writeSubtabHookSummaryInline(b *strings.Builder, sub SubtabSpec) {
	parts := []string{}
	if sub.List != nil {
		parts = append(parts, "list")
	}
	if sub.Open != nil {
		if sub.Open.Drill != nil {
			parts = append(parts, "open+drill")
		} else {
			parts = append(parts, "open")
		}
	}
	if sub.Chips != nil {
		parts = append(parts, "chips")
	}
	if sub.Activate != nil {
		parts = append(parts, "drill(activate)")
	}
	if sub.Sidebar != nil {
		parts = append(parts, "sidebar")
	}
	if len(parts) == 0 {
		b.WriteString("_no hooks_")
		return
	}
	b.WriteString(strings.Join(parts, " · "))
}

// BuildQAChecklistMarkdown derives the manual QA walk from the
// registry — the same table dispatch reads from — so a surface can't
// be forgotten: if it's reachable, it's on the list; if a hook is
// declared, its battery items appear. Regenerate after feature work
// (`go run ./cmd/inventory -qa`); tick boxes in a COPY, not the
// generated file.
func BuildQAChecklistMarkdown() string {
	var b strings.Builder
	b.WriteString("# sf-deck QA checklist (generated)\n\n")
	b.WriteString("Derived from tabRegistry by `go run ./cmd/inventory -qa` — do not\n")
	b.WriteString("hand-edit; regenerate after feature work. Walk top to bottom on a\n")
	b.WriteString("data-rich org, then spot-check empty states on a bare org and one\n")
	b.WriteString("pass at ~100-col width.\n\n")
	b.WriteString("## Global (once per session)\n\n")
	for _, item := range []string{
		"cold launch: org list paints from cache instantly, then refreshes",
		"org rail: 0 focuses, j/k switches org live, quick-jump letters, fold/expand, M manager",
		"org switch mid-list: no cursor/scroll bleed (wheel gate)",
		"narrow terminal: footer shows +N… marker; ? lists the full set",
		"? modal: Keybindings filter + edit, Tab → About page",
		"ctrl+f global search from cold launch",
		"ctrl+r global refresh; per-resource flashes",
		"settings modal: theme picker, limits, keybindings round-trip",
		"quit + relaunch: tabs/widths/chips/pins persist",
	} {
		fmt.Fprintf(&b, "- [ ] %s\n", item)
	}
	b.WriteString("\n")

	specs := tabSpecs()
	tops := []Tab{}
	drills := map[Tab][]Tab{}
	for t, s := range specs {
		if s.Stem == t {
			tops = append(tops, t)
		} else {
			drills[s.Stem] = append(drills[s.Stem], t)
		}
	}
	sort.Slice(tops, func(i, j int) bool { return int(tops[i]) < int(tops[j]) })
	for k := range drills {
		sort.Slice(drills[k], func(i, j int) bool { return int(drills[k][i]) < int(drills[k][j]) })
	}

	for _, t := range tops {
		spec := specs[t]
		fmt.Fprintf(&b, "## /%s\n\n", t.String())
		writeQABattery(&b, "", specForQA{spec: spec})
		for _, sub := range spec.Subtabs {
			fmt.Fprintf(&b, "### %s\n\n", sub.Label)
			writeQABattery(&b, "  ", specForQA{spec: spec, sub: &sub})
		}
		for _, dt := range drills[t] {
			ds := specs[dt]
			if ds == nil {
				continue
			}
			fmt.Fprintf(&b, "### drill: /%s\n\n", dt.String())
			writeQABattery(&b, "  ", specForQA{spec: ds, drill: true})
			for _, sub := range ds.Subtabs {
				fmt.Fprintf(&b, "#### %s\n\n", sub.Label)
				writeQABattery(&b, "    ", specForQA{spec: ds, sub: &sub, drill: true})
			}
		}
		b.WriteString("\n")
	}
	return b.String()
}

// specForQA resolves which hooks are effective for a (tab, subtab)
// pair — subtab shadows tab, mirroring tabspec_resolve.go.
type specForQA struct {
	spec  *TabSpec
	sub   *SubtabSpec
	drill bool
}

func (q specForQA) hasList() bool {
	if q.sub != nil && q.sub.List != nil {
		return true
	}
	return q.sub == nil && q.spec.List != nil
}
func (q specForQA) hasChips() bool {
	if q.sub != nil && q.sub.Chips != nil {
		return true
	}
	return q.sub == nil && q.spec.Chips != nil
}
func (q specForQA) hasOpen() bool {
	if q.sub != nil && q.sub.Open != nil {
		return true
	}
	return q.spec.Open != nil
}
func (q specForQA) hasDrill() bool {
	if q.sub != nil && q.sub.Open != nil && q.sub.Open.Drill != nil {
		return true
	}
	if q.spec.Open != nil && q.spec.Open.Drill != nil {
		return true
	}
	if q.sub != nil && q.sub.Activate != nil {
		return true
	}
	return q.spec.Activate != nil
}

func writeQABattery(b *strings.Builder, indent string, q specForQA) {
	item := func(s string) { fmt.Fprintf(b, "%s- [ ] %s\n", indent, s) }
	if q.spec.EnsureData != nil {
		item("loads on entry (cold + from cache); `r` refreshes; error state readable on a broken org")
	}
	if q.hasList() {
		item("`/` filters (and ranks sensibly); esc clears; cursor + scroll behave at list ends")
		item("`s` sort, `c` column mode, `}` snap, `z` zen — widths persist across relaunch")
		item("empty state renders a hint, not a blank pane")
	}
	if q.hasChips() {
		item("chips: ←/→ cycle, counts correct, `V` manager, `N` wizard round-trips, `F` pin")
	}
	if q.hasDrill() {
		item("`enter` drills; `esc` returns to the same row; number-key back-nav restores drill")
	}
	if q.hasOpen() {
		item("`o` opens the right Lightning page, `ctrl+o` lists every open target; `y` copies the URL, `ctrl+y` copies a value (label / API name / Id / SOQL …)")
	}
	if q.spec.Sidebar != nil || (q.sub != nil && q.sub.Sidebar != nil) {
		item("sidebar matches the cursored row; updates on move; `i` inspect when truncated")
	}
	if q.spec.RecordRecentVisit != nil && q.drill {
		item("drilling records a Recently-viewed entry (check the recent chip on the parent)")
	}
	b.WriteString("\n")
}
